#pragma once
void QueueStackMenu();
void QueueStackShow();
void QueueStackReverse();
void QueueStackAverse();
void QueueStackInit();
void QueueStackEnqueue();
void QueueStackDequeue();
void QueueStackDelete();
